apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-demo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-demo.fullname" . }}
    spec:
      containers:
        - name: {{ include "helm-demo.fullname" . }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: "/login"
              port: {{ .Values.service.port }}
          volumeMounts:
          - name: kibana-conf-volume
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
      volumes:
        - name: kibana-conf-volume
          configMap:
            name: kibana-conf

